import { Category, Product } from '@/types/product';
import { BRAND_IMAGES } from './images';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-earrings',
    name: 'Earrings',
    slug: 'earrings',
    description: 'Statement drops, everyday hoops, huggies, and dainty studs crafted to frame your face.',
    image: BRAND_IMAGES.categories.earrings,
    itemCount: 24,
    tagline: 'Effortless radiance',
    isActive: true,
  },
  {
    id: 'cat-pendants',
    name: 'Pendants',
    slug: 'pendants',
    description: 'Artisanal solitaires, coin medallions, and floral motifs designed for timeless charm.',
    image: BRAND_IMAGES.categories.pendants,
    itemCount: 18,
    tagline: 'Signature focal pieces',
    isActive: true,
  },
  {
    id: 'cat-kadas',
    name: 'Kadas',
    slug: 'kadas',
    description: 'Sculptural brass cuffs, textured bands, and traditional daily-wear kadas.',
    image: BRAND_IMAGES.categories.kadas,
    itemCount: 14,
    tagline: 'Bold wrist elegance',
    isActive: true,
  },
  {
    id: 'cat-bracelets',
    name: 'Bracelets',
    slug: 'bracelets',
    description: 'Delicate charm chains, tennis bracelets, and modern minimalist link bands.',
    image: BRAND_IMAGES.categories.bracelets,
    itemCount: 16,
    tagline: 'Subtle everyday sparkle',
    isActive: true,
  },
  {
    id: 'cat-enamel-kadas',
    name: 'Enamel Kadas',
    slug: 'enamel-kadas',
    description: 'Hand-painted meenakari and pastel enamel work crafted over 18k gold plating.',
    image: BRAND_IMAGES.categories.enamelKadas,
    itemCount: 12,
    tagline: 'Vibrant handcrafted art',
    isActive: true,
  },
  {
    id: 'cat-rings',
    name: 'Rings',
    slug: 'rings',
    description: 'Stackable minimalist bands, solitaire stones, and signet rings for daily wear.',
    image: BRAND_IMAGES.categories.rings,
    itemCount: 22,
    tagline: 'Modern daily staples',
    isActive: true,
  },
  {
    id: 'cat-wrist-chain',
    name: 'Wrist Chain',
    slug: 'wrist-chain',
    description: 'Fine beaded chains, sleek box links, and paperclip chains for effortless layering.',
    image: BRAND_IMAGES.categories.wristChain,
    itemCount: 15,
    tagline: 'Featherlight sophistication',
    isActive: true,
  },
  {
    id: 'cat-neck-chain',
    name: 'Neck Chain',
    slug: 'neck-chain',
    description: 'Herringbone, rope, figaro, and snake chains engineered for seamless layering.',
    image: BRAND_IMAGES.categories.neckChain,
    itemCount: 20,
    tagline: 'Layered perfection',
    isActive: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  // 1. Earrings
  {
    id: 'nz-001',
    name: 'Aria Baroque Pearl Drop Earrings',
    slug: 'aria-baroque-pearl-drop-earrings',
    category: 'earrings',
    categoryName: 'Earrings',
    sku: 'NZ-EAR-001',
    price: 1499,
    comparePrice: 1999,
    offerTag: '25% OFF',
    shortDescription: 'Naturally shaped baroque freshwater pearls suspended from 18k gold-plated huggies.',
    description: 'Crafted with authentic hand-selected baroque freshwater pearls, the Aria Drop Earrings offer an organic, luminous warmth. Each pearl has subtle natural variations, making every pair uniquely yours.',
    material: '18K Gold Plated Brass, Freshwater Baroque Pearls, Hypoallergenic Stainless Steel posts',
    colour: 'Warm Gold / Pearl White',
    careInstructions: 'Avoid direct contact with perfumes, lotions, and water. Store in the provided micro-fibre pouch.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
        alt: 'Aria Baroque Pearl Drop Earrings front view',
      },
      {
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
        alt: 'Aria Baroque Pearl Drop Earrings styled on model',
      },
    ],
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 18,
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: 'nz-002',
    name: 'Celeste Ribbed Gold Chunky Hoops',
    slug: 'celeste-ribbed-gold-chunky-hoops',
    category: 'earrings',
    categoryName: 'Earrings',
    sku: 'NZ-EAR-002',
    price: 1199,
    comparePrice: 1599,
    offerTag: '25% OFF',
    shortDescription: 'Hollow, featherweight vintage-inspired ribbed chunky gold hoop earrings.',
    description: 'The Celeste Hoops bring runway-ready drama without the weight. Engineered hollow for ultra-comfortable all-day wear with a secure latch closure.',
    material: '18K PVD Gold Plating over Anti-Tarnish Stainless Steel',
    colour: 'Polished Yellow Gold',
    careInstructions: 'Wipe with a soft cotton cloth after wearing. Water and sweat resistant.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
        alt: 'Celeste Ribbed Gold Chunky Hoops view',
      },
    ],
    isNewArrival: true,
    isBestseller: false,
    isFeatured: true,
    inStock: true,
    stockQuantity: 25,
    rating: 4.8,
    reviewCount: 29,
  },

  // 2. Pendants
  {
    id: 'nz-003',
    name: 'Solstice Sunburst Medallion Pendant',
    slug: 'solstice-sunburst-medallion-pendant',
    category: 'pendants',
    categoryName: 'Pendants',
    sku: 'NZ-PEN-003',
    price: 1399,
    comparePrice: 1899,
    offerTag: '26% OFF',
    shortDescription: 'An engraved sunburst talisman medallion suspended from a delicate satellite link.',
    description: 'Capturing radiant optimism, the Solstice Medallion features embossed rays around a sparkling central zircon, representing warmth, clarity, and grace.',
    material: '18K Gold Plated Brass, AAA Cubic Zirconia',
    colour: 'Warm Gold',
    careInstructions: 'Store in airtight pouch away from direct moisture.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        alt: 'Solstice Sunburst Medallion Pendant',
      },
    ],
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 14,
    rating: 5.0,
    reviewCount: 38,
  },
  {
    id: 'nz-004',
    name: 'Luna Emerald Teardrop Solitaire Pendant',
    slug: 'luna-emerald-teardrop-solitaire-pendant',
    category: 'pendants',
    categoryName: 'Pendants',
    sku: 'NZ-PEN-004',
    price: 1599,
    comparePrice: 2199,
    offerTag: '27% OFF',
    shortDescription: 'A vivid emerald green teardrop cubic zirconia framed in micro-pavé prongs.',
    description: 'Subtle vintage luxury designed for everyday elegance. The deep emerald green stone catches the light brilliantly from every angle.',
    material: '18K Micro Gold Plated Brass, Synthetic Emerald CZ',
    colour: 'Emerald Green & Gold',
    careInstructions: 'Avoid spraying perfumes directly onto the gemstone.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        alt: 'Luna Emerald Teardrop Solitaire Pendant',
      },
    ],
    isNewArrival: false,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 11,
    rating: 4.9,
    reviewCount: 51,
  },

  // 3. Kadas
  {
    id: 'nz-005',
    name: 'Rhea Sculptural Textured Gold Kada',
    slug: 'rhea-sculptural-textured-gold-kada',
    category: 'kadas',
    categoryName: 'Kadas',
    sku: 'NZ-KAD-005',
    price: 1899,
    comparePrice: 2499,
    offerTag: '24% OFF',
    shortDescription: 'A bold, hand-hammered open-cuff kada with contoured edges for effortless styling.',
    description: 'The Rhea Kada blends timeless royal grandeur with a modern, ergonomic open silhouette. Slightly adjustable to fit all wrist sizes securely.',
    material: 'Heavy 18K Gold Plated Brass with Anti-Tarnish Coating',
    colour: 'Rich Antique Gold',
    careInstructions: 'Keep dry and gently polish with microfiber cloth.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1611591475828-59154f9d651c?auto=format&fit=crop&w=800&q=80',
        alt: 'Rhea Sculptural Textured Gold Kada',
      },
    ],
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 16,
    rating: 4.9,
    reviewCount: 34,
  },
  {
    id: 'nz-006',
    name: 'Vira Twisted Rope Open Kada',
    slug: 'vira-twisted-rope-open-kada',
    category: 'kadas',
    categoryName: 'Kadas',
    sku: 'NZ-KAD-006',
    price: 1699,
    comparePrice: 2299,
    offerTag: '26% OFF',
    shortDescription: 'Dual entwined gold bands culminating in smooth rounded spherical ends.',
    description: 'A structural statement kada engineered with precision twisted lines that add depth and sophistication to both ethnic and contemporary ensembles.',
    material: 'Anti-Tarnish Surgical Grade Stainless Steel with 18K Gold PVD',
    colour: 'Mirror Gold',
    careInstructions: 'Water resistant and hypoallergenic. Wipe clean with soft cloth.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1611591475828-59154f9d651c?auto=format&fit=crop&w=800&q=80',
        alt: 'Vira Twisted Rope Open Kada',
      },
    ],
    isNewArrival: false,
    isBestseller: false,
    isFeatured: true,
    inStock: true,
    stockQuantity: 20,
    rating: 4.7,
    reviewCount: 19,
  },

  // 4. Bracelets
  {
    id: 'nz-007',
    name: 'Elysian Diamond Tennis Bracelet',
    slug: 'elysian-diamond-tennis-bracelet',
    category: 'bracelets',
    categoryName: 'Bracelets',
    sku: 'NZ-BRC-007',
    price: 1999,
    comparePrice: 2799,
    offerTag: '28% OFF',
    shortDescription: 'A continuous loop of brilliant prong-set 3mm AAA cubic zirconia crystals with safety clasp.',
    description: 'The epitome of quiet luxury. The Elysian Tennis Bracelet delivers dazzling high-refraction sparkle for gala evenings or understated daily layering.',
    material: '18K White Gold Plated Brass, AAA+ Cubic Zirconia',
    colour: 'Silver / White Gold',
    careInstructions: 'Keep in velvet box to maintain stone brilliance.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
        alt: 'Elysian Diamond Tennis Bracelet',
      },
    ],
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 12,
    rating: 5.0,
    reviewCount: 47,
  },
  {
    id: 'nz-008',
    name: 'Amara Paperclip & Pearl Charm Bracelet',
    slug: 'amara-paperclip-pearl-charm-bracelet',
    category: 'bracelets',
    categoryName: 'Bracelets',
    sku: 'NZ-BRC-008',
    price: 1299,
    comparePrice: 1799,
    offerTag: '27% OFF',
    shortDescription: 'Modern elongated links adorned with a genuine freshwater pearl pendant.',
    description: 'Chic, lightweight, and versatile. The toggle clasp allows seamless sizing adjustment for maximum comfort.',
    material: '18K Gold Plated Brass, Natural Freshwater Pearl',
    colour: 'Warm Gold',
    careInstructions: 'Avoid harsh chemicals and chlorinated water.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
        alt: 'Amara Paperclip & Pearl Charm Bracelet',
      },
    ],
    isNewArrival: false,
    isBestseller: false,
    isFeatured: true,
    inStock: true,
    stockQuantity: 22,
    rating: 4.8,
    reviewCount: 26,
  },

  // 5. Enamel Kadas
  {
    id: 'nz-009',
    name: 'Gulabi Lotus Hand-Painted Enamel Kada',
    slug: 'gulabi-lotus-hand-painted-enamel-kada',
    category: 'enamel-kadas',
    categoryName: 'Enamel Kadas',
    sku: 'NZ-ENM-009',
    price: 2199,
    comparePrice: 2999,
    offerTag: '26% OFF',
    shortDescription: 'Intricate blush pink and emerald green meenakari enamel with floral motifs.',
    description: 'An ode to royal heritage craftsmanship. Hand-enamelled by master artisans with delicate lotus blossoms and 18k micron gold finish.',
    material: 'Brass, Hand-Painted Artisan Enamel, 18K Micron Gold Finish',
    colour: 'Blush Pink, Sage Green & Gold',
    careInstructions: 'Store individually in velvet pouch to prevent surface scratches.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
        alt: 'Gulabi Lotus Hand-Painted Enamel Kada',
      },
    ],
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 9,
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: 'nz-010',
    name: 'Noor Ivory & Gold Geometric Enamel Kada',
    slug: 'noor-ivory-gold-geometric-enamel-kada',
    category: 'enamel-kadas',
    categoryName: 'Enamel Kadas',
    sku: 'NZ-ENM-010',
    price: 1999,
    comparePrice: 2699,
    offerTag: '25% OFF',
    shortDescription: 'Monochrome cream enamel inlay segmented with polished 18k gold bands.',
    description: 'A contemporary take on traditional enamel work. Crisp ivory tones paired with glistening gold for sophisticated modern festive dressing.',
    material: 'High-Grade Brass, Glossy Hard Enamel, 18K Gold Plated',
    colour: 'Ivory Cream & Polished Gold',
    careInstructions: 'Wipe with a soft dry cloth. Avoid exposure to high heat and water.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
        alt: 'Noor Ivory & Gold Geometric Enamel Kada',
      },
    ],
    isNewArrival: false,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 15,
    rating: 4.8,
    reviewCount: 22,
  },

  // 6. Rings
  {
    id: 'nz-011',
    name: 'Mira Emerald Solitaire Signet Ring',
    slug: 'mira-emerald-solitaire-signet-ring',
    category: 'rings',
    categoryName: 'Rings',
    sku: 'NZ-RNG-011',
    price: 1299,
    comparePrice: 1799,
    offerTag: '27% OFF',
    shortDescription: 'A smooth oval signet ring centred with a faceted emerald green cubic zirconia.',
    description: 'Subtle vintage opulence designed for everyday finger stacking. Polished to a mirror sheen with smooth inner comfort fit.',
    material: '18K Gold Plated Stainless Steel, Emerald Cubic Zirconia',
    colour: 'Warm Gold / Emerald Green',
    careInstructions: 'Waterproof and anti-tarnish. Clean with warm soapy water if needed.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
        alt: 'Mira Emerald Solitaire Signet Ring',
      },
    ],
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 28,
    rating: 4.9,
    reviewCount: 56,
  },
  {
    id: 'nz-012',
    name: 'Aurelia Triple Pavé Stacking Band Ring',
    slug: 'aurelia-triple-pave-stacking-band-ring',
    category: 'rings',
    categoryName: 'Rings',
    sku: 'NZ-RNG-012',
    price: 999,
    comparePrice: 1399,
    offerTag: '28% OFF',
    shortDescription: 'Three interlocking micro-pavé crystal bands for effortless finger layering.',
    description: 'A dazzling daily band featuring precision hand-set stones that shimmer with every gesture.',
    material: '18K Gold Plating, Hypoallergenic Brass, Micro CZ',
    colour: 'Yellow Gold & Clear Sparkle',
    careInstructions: 'Store in dry pouch. Remove before washing dishes.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
        alt: 'Aurelia Triple Pavé Stacking Band Ring',
      },
    ],
    isNewArrival: false,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 30,
    rating: 4.8,
    reviewCount: 41,
  },

  // 7. Wrist Chain
  {
    id: 'nz-013',
    name: 'Kira Sleek Box Link Wrist Chain',
    slug: 'kira-sleek-box-link-wrist-chain',
    category: 'wrist-chain',
    categoryName: 'Wrist Chain',
    sku: 'NZ-WRC-013',
    price: 899,
    comparePrice: 1299,
    offerTag: '30% OFF',
    shortDescription: 'Ultra-fine 1.5mm square box chain with lustrous mirror finish and lobster clasp.',
    description: 'Minimalist perfection. Featherweight and smooth against the skin, designed to be worn 24/7 without tarnishing.',
    material: 'Surgical Stainless Steel with 18K PVD Gold Plating',
    colour: 'High-Polish Gold',
    careInstructions: '100% Anti-Tarnish & Sweatproof. Wear during workouts and showers.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        alt: 'Kira Sleek Box Link Wrist Chain',
      },
    ],
    isNewArrival: true,
    isBestseller: false,
    isFeatured: true,
    inStock: true,
    stockQuantity: 35,
    rating: 4.9,
    reviewCount: 23,
  },
  {
    id: 'nz-014',
    name: 'Sia Dainty Beaded Satellite Wrist Chain',
    slug: 'sia-dainty-beaded-satellite-wrist-chain',
    category: 'wrist-chain',
    categoryName: 'Wrist Chain',
    sku: 'NZ-WRC-014',
    price: 949,
    comparePrice: 1399,
    offerTag: '32% OFF',
    shortDescription: 'Delicate cable chain punctuated with tiny polished gold beads every half inch.',
    description: 'An airy, delicate wrist chain that adds an understated shimmer to your everyday look.',
    material: '18K Gold Plated Stainless Steel',
    colour: 'Warm Gold',
    careInstructions: 'Tarnish-free. Wipe clean with soft cloth.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        alt: 'Sia Dainty Beaded Satellite Wrist Chain',
      },
    ],
    isNewArrival: false,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 24,
    rating: 4.8,
    reviewCount: 37,
  },

  // 8. Neck Chain
  {
    id: 'nz-015',
    name: 'Serena Layered Flat Herringbone Neck Chain',
    slug: 'serena-layered-flat-herringbone-neck-chain',
    category: 'neck-chain',
    categoryName: 'Neck Chain',
    sku: 'NZ-NCK-015',
    price: 1499,
    comparePrice: 1999,
    offerTag: '25% OFF',
    shortDescription: 'A silky-smooth 3mm flat herringbone snake chain that lies fluidly against collarbones.',
    description: 'Liquid gold around your neck. The Serena chain reflects ambient light with every turn, offering high-impact elegance for both tees and evening gowns.',
    material: '18K Gold PVD Coating over Anti-Tarnish Stainless Steel',
    colour: 'Lustrous Gold',
    careInstructions: 'Store flat to prevent kinking. Waterproof and tarnish resistant.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&q=80',
        alt: 'Serena Layered Flat Herringbone Neck Chain',
      },
    ],
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 20,
    rating: 5.0,
    reviewCount: 64,
  },
  {
    id: 'nz-016',
    name: 'Zara Twisted French Rope Neck Chain',
    slug: 'zara-twisted-french-rope-neck-chain',
    category: 'neck-chain',
    categoryName: 'Neck Chain',
    sku: 'NZ-NCK-016',
    price: 1399,
    comparePrice: 1899,
    offerTag: '26% OFF',
    shortDescription: 'Classic 2.5mm diamond-cut French rope chain offering dynamic 3D depth and shimmer.',
    description: 'An essential styling staple. Wear solo or layer with pendants and chokers for an elevated curated stack.',
    material: '18K Gold Plated Stainless Steel',
    colour: 'Deep Golden Shine',
    careInstructions: 'Anti-tarnish and water resistant. Wipe with cotton cloth.',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&q=80',
        alt: 'Zara Twisted French Rope Neck Chain',
      },
    ],
    isNewArrival: false,
    isBestseller: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 18,
    rating: 4.9,
    reviewCount: 45,
  },
];
